export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const GET_NOTE_BEGIN = "GET_NOTE_BEGIN";
export const GET_NOTE_SUCCESS = "GET_NOTE_SUCCESS";
export const GET_NOTE_FAIL = "GET_NOTE_FAIL";

export const GET_ALLGOALS_BEGIN = "GET_ALLGOALS_BEGIN";
export const GET_ALLGOALS_SUCCESS = "GET_ALLGOALS_SUCCESS";
export const GET_ALLGOALS_FAIL = "GET_ALLGOALS_FAIL";

export const UPDATE_NOTE_BEGIN = "UPDATE_NOTE_BEGIN";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
export const UPDATE_NOTE_FAIL = "UPDATE_NOTE_SUCCESS";

export const DELETE_NOTE_BEGIN = "DELETE_NOTE_BEGIN";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_FAIL = "DELETE_NOTE_FAIL";
