export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const GET_ALLGOALS_BEGIN = "GET_ALLGOALS_BEGIN";
export const GET_ALLGOALS_SUCCESS = "GET_ALLGOALS_SUCCESS";
export const GET_ALLGOALS_FAIL = "GET_ALLGOALS_FAIL";

export const GET_DETAILGOALS_BEGIN = "GET_DETAILGOALS_BEGIN";
export const GET_DETAILGOALS_SUCCESS = "GET_DETAILGOALS_SUCCESS";
export const GET_DETAILGOALS_FAIL = "GET_DETAILGOALS_FAIL";