export const GET_USER_BEGIN = "GET_USER_BEGIN";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const PUT_USER_BEGIN = "PUT_USER_BEGIN";
export const PUT_USER_SUCCESS = "PUT_USER_SUCCESS";
export const PUT_USER_FAIL = "PUT_USER_FAIL";

export const PUT_ALERT_SUCCESS = "PUT_ALERT_SUCCESS";
export const PUT_ALERT_BEGIN = "PUT_ALERT_BEGIN";

export const PUT_ALERT_PHOTO_BEGIN = "PUT_ALERT_PHOTO_BEGIN";
export const PUT_ALERT_PHOTO_SUCCESS = "PUT_ALERT_PHOTO_SUCCESS";
